# Generated by Django 6.0 on 2026-03-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_pick', models.PositiveIntegerField(default=1)),
                ('total_rounds', models.PositiveIntegerField(default=10)),
                ('pick_order', models.JSONField(help_text='JSON array of team IDs in pick order per round')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='game.league')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('pick_number', models.PositiveIntegerField()),
                ('pick_time', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='game.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='game.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='game.team')),
            ],
            options={
                'ordering': ['pick_number'],
                'unique_together': {('draft', 'player')},
            },
        ),
    ]
